---
- name: Подключение
  vars:
    token: "{{ lookup('file', '../../tokens/token-{{ type }}') }}"
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ advertise_addr }}"
    join_token: "{{ token }}"
