---
- name: "[{{ name }}] Создаём секрет"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ lookup('file', '.env') | b64encode }}"
    labels:
      secret: "{{ lookup('file', '.env') | hash('sha1') }}"
    data_is_b64: true
    state: present

- name: "[{{ name }}] Выкладываем сервис"
  community.docker.docker_swarm_service:
    name: "{{ name }}"
    image: localhost:5000/api:latest
    state: present
    publish:
      - mode: ingress
        protocol: tcp
        published_port: 3002
        target_port: 3000
    secrets:
      - secret_name: "{{ name }}.env"
        filename: "/opt/app/.env"
