galaxy_info:
  role_name: preconfig
  description: Настройка серверов для работы с Docker
  author: Anton Larichev
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
