---
- name: "[{{ name }}] Конфигурация секрета"
  block:

  - name: "[{{ name }}] Создаем секрет"
    include: "secret-create.yml"

  rescue:
    - name: "[{{ name }}] Удаляем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Создаем секрет"
      include: "secret-create.yml"