---
- name: Установка Docker
  block:

    - name: Установка дополнительных пакетов
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-pip
        update-cache: true
        cache_valid_time: 86400
        tags: extra_package

    - name: mkdir
      command: mkdir -p /etc/apt/keyrings

    - name: Добавление ключа Docker
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Установка стабильного репозитория
      apt_repository:
        repo: >
          deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Update apt 
      apt:
        upgrade: true
        update-cache: true
        cache_valid_time: 86400

    - name: Установка Docker
      apt:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        state: present

    - name: Docker check
      service:
        name: docker
        state: restarted
        enabled: true
  become: true

- name: Завершение установки Docker
  block:
    - name: Sudo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

  become: true

- name: Установка Docker-compose
  block:
    - name: Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-aarch64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

- name: Установка дополнительных пакетов python
  block:
  - name: Установка pip пакетов
    pip:
      name: docker

- name: Reboot
  block:
    - name: Перезагрузка сервера
      reboot:
  become: true